In [12]:
!pip install bs4
!pip install requests

Requirement already satisfied: bs4 in c:\users\nirav\anaconda3\lib\site-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in c:\users\nirav\anaconda3\lib\site-packages (from bs4) (4.10.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\nirav\anaconda3\lib\site-packages (from beautifulsoup4->bs4) (2.2.1)
Requirement already satisfied: requests in c:\users\nirav\anaconda3\lib\site-packages (2.26.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\nirav\anaconda3\lib\site-packages (from requests) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\nirav\anaconda3\lib\site-packages (from requests) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\nirav\anaconda3\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\nirav\anaconda3\lib\site-packages (from requests) (3.2)

In [18]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\nirav\anaconda3\lib\site-packages (4.1.3)
Requirement already satisfied: trio~=0.17 in c:\users\nirav\anaconda3\lib\site-packages (from selenium) (0.20.0)
Requirement already satisfied: urllib3[secure,socks]~=1.26 in c:\users\nirav\anaconda3\lib\site-packages (from selenium) (1.26.7)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\nirav\anaconda3\lib\site-packages (from selenium) (0.9.2)
Requirement already satisfied: cffi>=1.14 in c:\users\nirav\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.14.6)
Requirement already satisfied: attrs>=19.2.0 in c:\users\nirav\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.2.0)
Requirement already satisfied: idna in c:\users\nirav\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.2)
Requirement already satisfied: sniffio in c:\users\nirav\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: async-generator>=1.9 in c:\users\nirav\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: sortedcontainers in c:\users\nirav\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: outcome in c:\users\nirav\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.1.0)
Requirement already satisfied: pycparser in c:\users\nirav\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.20)
Requirement already satisfied: wsproto>=0.14 in c:\users\nirav\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.1.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\nirav\anaconda3\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: pyOpenSSL>=0.14 in c:\users\nirav\anaconda3\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (21.0.0)
Requirement already satisfied: cryptography>=1.3.4 in c:\users\nirav\anaconda3\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (3.4.8)
Requirement already satisfied: certifi in c:\users\nirav\anaconda3\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (2021.10.8)
Requirement already satisfied: six>=1.5.2 in c:\users\nirav\anaconda3\lib\site-packages (from pyOpenSSL>=0.14->urllib3[secure,socks]~=1.26->selenium) (1.16.0)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\nirav\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.13.0)

In [19]:
# import libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

In [287]:
import time

In [20]:
# Importing selenium webdriver 
from selenium import webdriver

In [21]:
# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

In [22]:
#Importing requests
import requests

In [23]:
# importing regex
import re

# Scrape the details of most viewed videos on YouTube from Wikipedia.
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
You need to find following details:
A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [24]:
#connect to webdriver
driver=webdriver.Chrome("chromedriver.exe")
time.sleep(2)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/2300614395.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome("chromedriver.exe")

In [25]:
# to get url
driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")

In [26]:
Rank=[]
Name=[] 
Artist=[]
Upload_date=[]
Views=[]

In [27]:

dt = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[1]')
for d in dt:
    if d.text is None :
        Rank.append('-')
    else:
        Rank.append(d.text)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/599926877.py:1: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  dt = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[1]')

In [28]:
dt = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[2]')
for d in dt:
    if d.text is None :
        Name.append('-')
    else:
        Name.append(d.text)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/2999464878.py:1: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  dt = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[2]')

In [29]:
dt = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[3]')
for d in dt:
    if d.text is None :
        Artist.append('-')
    else:
        Artist.append(d.text)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/2725512465.py:1: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  dt = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[3]')

In [30]:
dt = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[5]')
for d in dt:
    if d.text is None :
        Upload_date.append('-')
    else:
        Upload_date.append(d.text)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/1912423871.py:1: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  dt = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[5]')

In [32]:
dt = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[4]')
for d in dt:
    if d.text is None :
        Views.append('-')
    else:
        Views.append(d.text)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/4281142392.py:1: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  dt = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[4]')

In [33]:
import pandas as pd
table=pd.DataFrame({})

table['Rank']=Rank
table['Name']=Name
table['Artist']=Artist
table['Upload Date']=Upload_date
table['Views']=Views

In [34]:
table

,Rank,Name,Artist,Upload Date,Views
0,1.,"""Baby Shark Dance""[3]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",10.72
1,2.,"""Despacito""[6]",Luis Fonsi,"January 12, 2017",7.85
2,3.,"""Johny Johny Yes Papa""[12]",LooLoo Kids,"October 8, 2016",6.36
3,4.,"""Shape of You""[13]",Ed Sheeran,"January 30, 2017",5.72
4,5.,"""See You Again""[15]",Wiz Khalifa,"April 6, 2015",5.52
5,6.,"""Bath Song""[20]",Cocomelon – Nursery Rhymes,"May 2, 2018",5.40
6,7.,"""Phonics Song with Two Words""[21]",ChuChu TV,"March 6, 2014",4.64
7,8.,"""Uptown Funk""[22]",Mark Ronson,"November 19, 2014",4.58
8,9.,"""Learning Colors – Colorful Eggs on a Farm""[23]",Miroshka TV,"February 27, 2018",4.57
9,10.,"""Masha and the Bear – Recipe for Disaster""[24]",Get Movies,"January 31, 2012",4.49
10,11.,"""Gangnam Style""[25]",Psy,"July 15, 2012",4.43
11,12.,"""Wheels on the Bus""[30]",Cocomelon – Nursery Rhymes,"May 24, 2018",4.08
12,13.,"""Dame Tu Cosita""[31]",El Chombo,"April 5, 2018",3.94
13,14.,"""Sugar""[32]",Maroon 5,"January 14, 2015",3.69
14,15.,"""Roar""[33]",Katy Perry,"September 5, 2013",3.58
15,16.,"""Counting Stars""[34]",OneRepublic,"May 31, 2013",3.58
16,17.,"""Sorry""[35]",Justin Bieber,"October 22, 2015",3.54
17,18.,"""Thinking Out Loud""[36]",Ed Sheeran,"October 7, 2014",3.45
18,19.,"""Axel F""[37]",Crazy Frog,"June 16, 2009",3.36
19,20.,"""Girls Like You""[38]",Maroon 5,"May 31, 2018",3.29
20,21.,"""Faded""[39]",Alan Walker,"December 3, 2015",3.28
21,22.,"""Dark Horse""[40]",Katy Perry,"February 20, 2014",3.27
22,23.,"""Baa Baa Black Sheep""[41]",Cocomelon – Nursery Rhymes,"June 25, 2018",3.24
23,24.,"""Let Her Go""[42]",Passenger,"July 25, 2012",3.23
24,25.,"""Bailando""[43]",Enrique Iglesias,"April 11, 2014",3.21
25,26.,"""Lean On""[44]",Major Lazer,"March 22, 2015",3.21
26,27.,"""Shake It Off""[45]",Taylor Swift,"August 18, 2014",3.17
27,28.,"""Perfect""[46]",Ed Sheeran,"November 9, 2017",3.17
28,29.,"""Waka Waka (This Time for Africa)""[47]",Shakira,"June 4, 2010",3.14
29,30.,"""Mi Gente""[48]",J Balvin,"June 29, 2017",3.08
30,"""Baby Shark Dance""[3]",Pinkfong Baby Shark - Kids' Songs & Stories,"7,046,700,000","November 2, 2020","June 17, 2016"
31,"""Despacito""[6]",Luis Fonsi,"3,002,800,000","August 4, 2017","January 12, 2017"
32,"""See You Again""[15]",Wiz Khalifa,"2,894,000,000","July 10, 2017","April 6, 2015"
33,"""Gangnam Style""⁂[25]",Psy,"803,700,000","November 24, 2012","July 15, 2012"
34,"""Baby""*[59]",Justin Bieber,"245,400,000","July 16, 2010","February 19, 2010"
35,"""Bad Romance""[63]",Lady Gaga,"178,400,000","April 14, 2010","November 24, 2009"
36,"""Charlie Bit My Finger""‡[67]",HDCYT,"128,900,000","October 25, 2009","May 22, 2007"
37,"""Evolution of Dance""[69]",Judson Laipply,"118,900,000","May 2, 2009","April 6, 2006"
38,"""Girlfriend""‡[71][72]",RCA Records,"92,600,000","July 17, 2008","February 27, 2007"
39,"""Evolution of Dance""[69]",Judson Laipply,"78,400,000","March 15, 2008","April 6, 2006"
40,"""Music Is My Hot Hot Sex""‡[76]",CLARUSBARTEL72,"76,600,000","March 1, 2008","April 9, 2007"
41,"""Evolution of Dance""*[69]",Judson Laipply,"10,600,000","May 19, 2006","April 6, 2006"
42,"""Pokemon Theme Music Video""‡[82]",Smosh,"4,300,000","March 12, 2006","November 28, 2005"
43,"""Myspace – The Movie""‡[87][88]",eggtea,"2,700,000","February 18, 2006","January 31, 2006"
44,"""Phony Photo Booth""‡[91]",mugenized,"3,400,000","January 21, 2006","December 1, 2005"
45,"""The Chronic of Narnia Rap""‡[93]",youtubedude,"2,300,000","January 9, 2006","December 18, 2005"
46,"""Ronaldinho: Touch of Gold""‡*[95]",Nikesoccer,"255,000","October 31, 2005","October 21, 2005"
47,"""I/O Brush""‡*[98]",larfus,"247,000","October 29, 2005","October 5, 2005"
48,"""Me at the zoo""[100]",jawed,1,"April 23, 2005","April 23, 2005"

In [35]:
driver.close()

# Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Match title (I.e. 1
st ODI)
B) Series
C) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [76]:
#connect to webdriver
driver=webdriver.Chrome("chromedriver.exe")

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/229302933.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome("chromedriver.exe")

In [62]:
# to get url
driver.get("https://www.bcci.tv/")

In [65]:
#click on international
international=driver.find_element_by_xpath("/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a")
international.click()

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/505287195.py:2: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  international=driver.find_element_by_xpath("/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a")

In [73]:
#Creating Empty list
Match_title1=[]
Series1=[]
Place1=[]
Date1=[]
Time1=[]

In [74]:
#Scraping Match_title
match_title= driver.find_elements_by_xpath("//span[@class='matchOrderText ng-binding ng-scope']")
for i in match_title:
    Match_title1.append(i.text)
    
#Scraping Series
series= driver.find_elements_by_xpath("//span[@class='ng-binding']")
for i in series:
    Series1.append(i.text)
    
#Scraping Place
place= driver.find_elements_by_xpath("//div[@class='fix-place ng-binding ng-scope']/span[2]")
for i in place:
    Place1.append(i.text)   
    
#Scraping Date
date= driver.find_elements_by_xpath("//h5[@class='ng-binding']")
for i in date:
    Date1.append(i.text)   
    
#Scraping Time
time= driver.find_elements_by_xpath("//h5[@class='text-right ng-binding']")
for i in time:
    Time1.append(i.text) 

Fixture=pd.DataFrame({})
Fixture['Match_title1']=Match_title1
Fixture['Series1']=Series1
Fixture['Place1']=Place1
Fixture['Date1']=Date1
Fixture['Time1']=Time1
Fixture

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/668542041.py:2: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  match_title= driver.find_elements_by_xpath("//span[@class='matchOrderText ng-binding ng-scope']")
C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/668542041.py:7: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  series= driver.find_elements_by_xpath("//span[@class='ng-binding']")
C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/668542041.py:12: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  place= driver.find_elements_by_xpath("//div[@class='fix-place ng-binding ng-scope']/span[2]")
C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/668542041.py:17: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  date= driver.find_elements_by_xpath("//h5[@class='ng-binding']")
C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/668542041.py:22: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  time= driver.find_elements_by_xpath("//h5[@class='text-right ng-binding']")

,Match_title1,Series1,Place1,Date1,Time1
0,2nd T20I -,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"Barabati Stadium,",12 JUN 2022,7:00 PM IST
1,3rd T20I -,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"Dr YS Rajasekhara Reddy ACA-VDCA Cricket Stadium,",14 JUN 2022,7:00 PM IST
2,4th T20I -,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"Saurashtra Cricket Association Stadium,",17 JUN 2022,7:00 PM IST
3,5th T20I -,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"M Chinnaswamy Stadium,",19 JUN 2022,7:00 PM IST

In [75]:
driver.close()

# Scrape the details of selenium exception from guru99.com.
Url = https://www.guru99.com/
You need to find following details:
A) Name
B) Description
Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [78]:
#connect to webdriver
driver=webdriver.Chrome("chromedriver.exe")

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/229302933.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome("chromedriver.exe")

In [79]:
# to get url
driver.get("https://www.guru99.com/")

In [80]:
driver.find_element_by_xpath('//a[@title="Selenium"]').click()

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/191405855.py:1: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  driver.find_element_by_xpath('//a[@title="Selenium"]').click()

In [81]:
driver.find_element_by_xpath('//a[@title="Selenium Exception Handling (Common Exceptions List)"]').click()

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/472190259.py:1: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  driver.find_element_by_xpath('//a[@title="Selenium Exception Handling (Common Exceptions List)"]').click()

In [82]:
Name=[]
Description=[]

In [83]:
dt = driver.find_elements_by_xpath('//table[@class="table table-striped"]/tbody/tr/td[1]')
for d in dt:
    Name.append(d.text)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/2594434453.py:1: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  dt = driver.find_elements_by_xpath('//table[@class="table table-striped"]/tbody/tr/td[1]')

In [84]:
dt = driver.find_elements_by_xpath('//table[@class="table table-striped"]/tbody/tr/td[2]')
for d in dt:
    Description.append(d.text)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/168012624.py:1: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  dt = driver.find_elements_by_xpath('//table[@class="table table-striped"]/tbody/tr/td[2]')

In [85]:
import pandas as pd
table=pd.DataFrame({})

table['Name']=Name
table['Description']=Description

In [86]:
table

,Name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

In [87]:
driver.close()

# Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details:
A) Rank
B) State
C) GSDP(18-19)
D) GSDP(17-18)
E) Share(2017)
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code.

In [92]:
driver=webdriver.Chrome("chromedriver.exe") 

url = "http://statisticstimes.com/"
driver.get(url)
driver.maximize_window()

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/1839783375.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome("chromedriver.exe")

In [97]:
#Click Economy
Economy=driver.find_element_by_xpath("/html/body/div[2]/div[1]/div[2]/div[2]/button")
Economy.click()

#Click India
India= driver.find_element_by_xpath("/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]")
India.click()

#Click on India GPD
GDP=driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[2]/ul/li[1]/a")
GDP.click()

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/1616693007.py:2: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  Economy=driver.find_element_by_xpath("/html/body/div[2]/div[1]/div[2]/div[2]/button")
C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/1616693007.py:6: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  India= driver.find_element_by_xpath("/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]")
C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/1616693007.py:10: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  GDP=driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[2]/ul/li[1]/a")

In [98]:
# Empty lists
Rank = []
State = []
GSDP1 = []
GSDP2  = []
Share = []
GDP_billion = []

In [99]:
try: # Scraping Rank
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[1]"):
        Rank.append(i.text)
except NoSuchElementException as e:
    print("No such element present")
    
try: # Scraping Name
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[2]"):
        State.append(i.text)
except NoSuchElementException as e:
    print("No such element present")
    
try: # Scraping GSDP1
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[3]"):
        GSDP1.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping GSDP2
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[4]"):
        GSDP2.append(i.text)
except NoSuchElementException as e:
    print("-")

try: # Scraping share
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[5]"):
        Share.append(i.text)
except NoSuchElementException as e:
    print("-")    
try: # Scraping GDP billion
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[6]"):
        GDP_billion.append(i.text)
except NoSuchElementException as e:
    print("-")

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/2580323002.py:2: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[1]"):
C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/2580323002.py:8: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[2]"):
C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/2580323002.py:14: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[3]"):
C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/2580323002.py:20: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[4]"):
C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/2580323002.py:26: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[5]"):
C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/2580323002.py:31: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[6]"):

In [100]:
# Creating data frame 
stats = pd.DataFrame({"Rank":Rank, "State":State, "GSDP (Cr INR at Current prices) (19-20)":GSDP1,
                      "GSDP (Cr INR at Current prices) (18-19)":GSDP2, "Share (18-19)":Share, 
                      "GDP ($ billion)":GDP_billion})
stats

,Rank,State,GSDP (Cr INR at Current prices) (19-20),GSDP (Cr INR at Current prices) (18-19),Share (18-19),GDP ($ billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
...,...,...,...,...,...,...
61,29,Sikkim,"28,391","25,141",0.15%,"17,060"
62,30,Nagaland,-,"24,534",0.15%,-
63,31,Arunachal Pradesh,-,"22,488",0.13%,-
64,32,Mizoram,"24,424","20,947",0.13%,"17,797"
65,33,Andaman & Nicobar Islands,-,-,-,-

In [101]:
driver.close()

# Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used
Note: - From the home page you have to click on the trending option from Explore menu through code.

In [113]:
#connect to webdriver
driver=webdriver.Chrome("chromedriver.exe")

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/229302933.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome("chromedriver.exe")

In [114]:
url = "https://github.com/"
driver.get(url)
driver.maximize_window()

In [115]:
explore = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary")
explore.click()

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/1506245622.py:1: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  explore = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary")

In [116]:
trending = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a")
trending.click()

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/2676719737.py:1: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  trending = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a")

In [117]:
# Empty list
Repository = []
Repository_des = []
Contributors = []
Language = []

In [118]:
try: # Scraping repository
    for i in driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a"):
        Repository.append(i.text)
except NoSuchElementException as e:
    print("-")

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/1701055609.py:2: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a"):

In [119]:
try: # Scraping Repository description
    for i in driver.find_elements_by_xpath("//p[@class='col-9 color-fg-muted my-1 pr-4']"):
        Repository_des.append(i.text)
except NoSuchElementException as e:
    print("-")

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/3029329018.py:2: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//p[@class='col-9 color-fg-muted my-1 pr-4']"):

In [120]:
try: # Scraping Contributors count
    for i in driver.find_elements_by_xpath("//*[@id='js-pjax-container']/div[3]/div/div[2]/article/div[2]/a[2]"):
        Contributors.append(i.text)
except NoSuchElementException as e:
    print("-")

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/2269654381.py:2: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//*[@id='js-pjax-container']/div[3]/div/div[2]/article/div[2]/a[2]"):

In [121]:
try: # Scraping language
    for i in driver.find_elements_by_xpath("//span[@class='d-inline-block ml-0 mr-3']"):
        Language.append(i.text)
except NoSuchElementException as e:
    print("-")

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/3861437318.py:2: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//span[@class='d-inline-block ml-0 mr-3']"):

In [122]:
print(len(Language))

22

In [123]:
# Creating data frame 
github = pd.DataFrame({"Repository title":Repository[:22],"Repository description":Repository_des[:22],
                       "Contributors count": Contributors[:22],"Language used": Language[:22]})
github

,Repository title,Repository description,Contributors count,Language used
0,atom / atom,The hackable text editor,"17,330",JavaScript
1,saharmor / dalle-playground,A playground to generate images from any text ...,222,JavaScript
2,borisdayma / dalle-mini,DALL·E Mini - Generate images from a text prompt,350,Python
3,openai / DALL-E,PyTorch package for the discrete VAE used for ...,"1,171",Python
4,microsoft / Data-Science-For-Beginners,"10 Weeks, 20 Lessons, Data Science for All!","2,334",Jupyter Notebook
5,microsoft / ML-For-Beginners,"12 weeks, 26 lessons, 52 quizzes, classic Mach...","7,385",Jupyter Notebook
6,papers-we-love / papers-we-love,Papers from the computer science community to ...,"4,851",Shell
7,vaxerski / Hyprland,Hyprland is a dynamic tiling Wayland composito...,25,C++
8,NVlabs / eg3d,"24 Lessons, 12 Weeks, Get Started as a Web Dev...",100,Python
9,microsoft / Web-Dev-For-Beginners,High performance Spigot fork that aims to fix ...,"7,732",JavaScript
10,PaperMC / Paper,Lightning-fast and Powerful Code Editor writte...,"1,586",Java
11,lapce / lapce,💬 Open source machine learning framework to au...,301,Rust
12,RasaHQ / rasa,📚 技术面试必备基础知识、Leetcode、计算机操作系统、计算机网络、系统设计,"4,015",Python
13,CyC2018 / CS-Notes,This repo includes Books and imp notes related...,"48,051",JavaScript
14,tvbb / z,⚙️ NGINX config generator on steroids 💉,63,Python
15,ahmedtariq01 / Cloud-DevOps-Learning-Resources,A Human-in-the-Loop workflow for creating HD i...,85,TypeScript
16,digitalocean / nginxconfig.io,A new full-featured and high-performance TypeS...,"1,374",Python
17,jina-ai / dalle-flow,中国程序员容易发音错误的单词,63,C++
18,deepkit / deepkit-framework,An open-source C++ library developed and used ...,61,JavaScript
19,shimohq / chinese-programmer-wrong-pronunciation,"Fast and low overhead web framework, for Node.js","1,365",Kotlin
20,facebook / folly,A fully functional Android app built entirely ...,"4,656",Go
21,fastify / fastify,"Like Prometheus, but for logs.","1,728",Go

In [124]:
driver.close()

# Scrape the details of top 100 songs on billiboard.com.
Url = https:/www.billboard.com/
You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
Note: - From the home page you have to click on the charts option then hot 100-page link through code

In [273]:
#connect to webdriver
driver=webdriver.Chrome("chromedriver.exe")

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/229302933.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome("chromedriver.exe")

In [274]:
url = "https://www.billboard.com/"
driver.get(url)

In [275]:
driver.find_element_by_xpath("/html/body/div[3]/header/div[1]/div/div/div[2]/div/nav/ul/li[1]").click()

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/1377110556.py:1: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  driver.find_element_by_xpath("/html/body/div[3]/header/div[1]/div/div/div[2]/div/nav/ul/li[1]").click()

In [276]:
driver.find_element_by_xpath("/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[3]/a").click()

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/3806476340.py:1: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  driver.find_element_by_xpath("/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[3]/a").click()

In [277]:
#Create empty list
Name = []
Artist = []

In [289]:
#scraping song names
try:
    names=driver.find_elements_by_xpath("//div[@class='o-chart-results-list-row-container']//h3")
    for i in names:
        Name.append(i.text)
except NoSuchElementException:       
    Name.append('No details available')
time.sleep(2)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/801619449.py:3: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  names=driver.find_elements_by_xpath("//div[@class='o-chart-results-list-row-container']//h3")

In [290]:
#scraping artist names
try:
    artist=driver.find_elements_by_xpath("//li[@class='lrv-u-width-100p']//span")
    for i in artist:
        Artist.append(i.text)
except NoSuchElementException:     
    Artist.append('-')
time.sleep(2)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/3032585980.py:3: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  artist=driver.find_elements_by_xpath("//li[@class='lrv-u-width-100p']//span")

In [296]:
#Scraping data of last week ranks, peak POS, and weeks on chart
Data = []

data = driver.find_elements_by_xpath('//span[@class="c-label  a-font-primary-m lrv-u-padding-tb-050@mobile-max"]')
for i in data:
    Data.append(i.text)


#Creating a new list to store only the text data
clean_Data = []

for i in Data:
    if i.strip():
        clean_Data.append(i)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/3316158047.py:4: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  data = driver.find_elements_by_xpath('//span[@class="c-label  a-font-primary-m lrv-u-padding-tb-050@mobile-max"]')

In [297]:
#Scraping data of last week ranks, peak POS, and weeks on chart for the first entry seperately

#Creating empty list
Data1 = []

data1 = driver.find_elements_by_xpath('//span[@class="c-label  a-font-primary-bold-l a-font-primary-m@mobile-max u-font-weight-normal@mobile-max lrv-u-padding-tb-050@mobile-max u-font-size-32@tablet"]')

for i in data1:
    Data1.append(i.text)

Data1

#Creating a new list to store only the text data
clean_Data1 = []

for i in Data1:
    if i.strip():
        clean_Data1.append(i)
        
clean_Data1

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/387835995.py:6: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  data1 = driver.find_elements_by_xpath('//span[@class="c-label  a-font-primary-bold-l a-font-primary-m@mobile-max u-font-weight-normal@mobile-max lrv-u-padding-tb-050@mobile-max u-font-size-32@tablet"]')

['1', '1', '9']

In [298]:
#Scraping data of last week ranks

#Creating empty list
LWR = []

for i in clean_Data[::3]:
    LWR.append(i)
    
LWR

#Creating empty list
LWR1 = []

for i in clean_Data1[0::3]:
    LWR1.append(i)
    
LWR1

#Concatenating the lists
LWR1.extend(LWR)

LWR1

['1',
 '2',
 '3',
 '5',
 '6',
 '7',
 '10',
 '-',
 '4',
 '12',
 '16',
 '11',
 '23',
 '17',
 '18',
 '28',
 '19',
 '27',
 '35',
 '33',
 '26',
 '-',
 '48',
 '36',
 '40',
 '31',
 '37',
 '34',
 '38',
 '32',
 '51',
 '44',
 '39',
 '45',
 '47',
 '50',
 '43',
 '46',
 '20',
 '42',
 '8',
 '9',
 '52',
 '60',
 '53',
 '13',
 '-',
 '57',
 '58',
 '63',
 '49',
 '41',
 '86',
 '64',
 '65',
 '54',
 '66',
 '14',
 '-',
 '-',
 '15',
 '56',
 '55',
 '67',
 '21',
 '74',
 '69',
 '68',
 '62',
 '75',
 '-',
 '59',
 '71',
 '72',
 '22',
 '25',
 '24',
 '70',
 '82',
 '90',
 '29',
 '-',
 '61',
 '80',
 '77',
 '-',
 '-',
 '30',
 '88',
 '76',
 '-',
 '-',
 '83',
 '99',
 '87',
 '84',
 '-',
 '-',
 '-',
 '-']

In [299]:
#Creating empty list
Peak_POS = []

for i in clean_Data[1::3]:
    Peak_POS.append(i)
    
Peak_POS

#Creating empty list
Peak_POS1 = []

for i in clean_Data1[1::3]:
    Peak_POS1.append(i)
    
Peak_POS1

#Concatenating the lists
Peak_POS1.extend(Peak_POS)

Peak_POS1

['1',
 '1',
 '1',
 '4',
 '1',
 '3',
 '7',
 '8',
 '4',
 '1',
 '5',
 '5',
 '9',
 '4',
 '5',
 '16',
 '7',
 '2',
 '19',
 '3',
 '6',
 '22',
 '23',
 '4',
 '15',
 '14',
 '21',
 '8',
 '7',
 '6',
 '28',
 '32',
 '4',
 '25',
 '15',
 '26',
 '29',
 '18',
 '3',
 '40',
 '8',
 '9',
 '15',
 '44',
 '14',
 '13',
 '47',
 '48',
 '49',
 '34',
 '7',
 '5',
 '53',
 '51',
 '55',
 '38',
 '43',
 '14',
 '59',
 '60',
 '15',
 '16',
 '18',
 '38',
 '21',
 '66',
 '22',
 '27',
 '12',
 '53',
 '71',
 '59',
 '13',
 '43',
 '22',
 '25',
 '24',
 '22',
 '64',
 '80',
 '29',
 '72',
 '13',
 '32',
 '31',
 '86',
 '87',
 '30',
 '52',
 '21',
 '91',
 '40',
 '11',
 '94',
 '51',
 '12',
 '97',
 '98',
 '99',
 '100']

In [300]:
#Scraping data of weeks on board

#Creating empty list
WOB = []

for i in clean_Data[2::3]:
    WOB.append(i)
    
WOB

#Creating empty list
WOB1 = []

for i in clean_Data1[2::3]:
    WOB1.append(i)
    
WOB1

#Concatenating the lists
WOB1.extend(WOB)

WOB1

['9',
 '8',
 '5',
 '7',
 '72',
 '32',
 '4',
 '21',
 '2',
 '47',
 '4',
 '28',
 '29',
 '4',
 '36',
 '16',
 '44',
 '49',
 '18',
 '30',
 '3',
 '1',
 '9',
 '38',
 '12',
 '4',
 '13',
 '37',
 '39',
 '4',
 '21',
 '11',
 '5',
 '6',
 '16',
 '4',
 '3',
 '34',
 '3',
 '6',
 '2',
 '2',
 '6',
 '17',
 '8',
 '2',
 '1',
 '9',
 '26',
 '4',
 '3',
 '3',
 '4',
 '6',
 '5',
 '14',
 '15',
 '2',
 '1',
 '1',
 '2',
 '4',
 '4',
 '9',
 '2',
 '2',
 '12',
 '20',
 '4',
 '18',
 '1',
 '2',
 '8',
 '14',
 '2',
 '2',
 '2',
 '4',
 '19',
 '9',
 '2',
 '2',
 '3',
 '4',
 '4',
 '1',
 '1',
 '2',
 '19',
 '4',
 '1',
 '10',
 '5',
 '2',
 '4',
 '5',
 '1',
 '1',
 '1',
 '1']

In [302]:
#Creating a dataframe for the scrapped data
billboard=pd.DataFrame({'Song':Name[::4][:100],'Artist':Artist[::7][:100],'Last week Rank':LWR1,'Peak Rank':Peak_POS1,'Weeks on board':WOB1})
billboard

,Song,Artist,Last week Rank,Peak Rank,Weeks on board
0,As It Was,Harry Styles,1,1,9
1,First Class,Jack Harlow,2,1,8
2,Wait For U,Future Featuring Drake & Tems,3,1,5
3,About Damn Time,Lizzo,5,4,7
4,Heat Waves,Glass Animals,6,1,72
...,...,...,...,...,...
95,Love You Better,Future,84,12,5
96,Wild Hearts,Keith Urban,-,97,1
97,Last Night Lonely,Jon Pardi,-,98,1
98,7500 OBO,Tim McGraw,-,99,1
99,Until I Found You,Stephen Sanchez,-,100,1

In [303]:
driver.close()

# Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/
You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location
Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
click on search. All this should be done through code

In [304]:
#connect to webdriver
driver=webdriver.Chrome("chromedriver.exe")

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/229302933.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome("chromedriver.exe")

In [305]:
url = "https://www.naukri.com/"
driver.get(url)

In [306]:
rec = driver.find_element_by_xpath("/html/body/div/div[2]/div[1]/div/ul/li[1]/a")
page_url = rec.get_attribute("href")

driver.get(page_url)
time.sleep(3)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/2825415941.py:2: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  rec = driver.find_element_by_xpath("/html/body/div/div[2]/div[1]/div/ul/li[1]/a")

In [307]:
#click on recruiters link
recruiters=driver.find_element_by_xpath("//a[@title='Search Recruiters']")
driver.get(recruiters.get_attribute('href'))
time.sleep(1)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/937167577.py:2: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  recruiters=driver.find_element_by_xpath("//a[@title='Search Recruiters']")

In [308]:
search=driver.find_element_by_xpath("//input[@class='sugInp']")
search.send_keys("Data Science")
time.sleep(1)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/1264006988.py:2: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  search=driver.find_element_by_xpath("//input[@class='sugInp']")

In [309]:
#click on search button
button=driver.find_element_by_xpath("//button[@id='qsbFormBtn']")
button.click()
time.sleep(1)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/3849006816.py:2: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  button=driver.find_element_by_xpath("//button[@id='qsbFormBtn']")

In [319]:
#create empty list
Name1 = []
Designation1 = []
Company1 = []
Skills1 = []
Location1 = []

In [320]:
#scrape names
try:
    names=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/a[1]")
    for i in names:
        Name1.append(i.text)
except NoSuchElementException:           #handling no such element exception
    Name1.append('No details available')

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/1654350520.py:3: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  names=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/a[1]")

In [321]:
#Add sleeptime    
time.sleep(2)

In [322]:
#scrape designation
try:
    designation_list=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/span[1]")
    for i in designation_list:
        Designation1.append(i.text)
except NoSuchElementException:        #handling no such element exception
    Designation1.append('No details available')

#Adding sleeptime    
time.sleep(2)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/1874377974.py:3: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  designation_list=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/span[1]")

In [323]:
#scrape company names
try:
    companies=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/a[2]")
    for i in companies:
        Company1.append(i.text)
except NoSuchElementException:#handling no such element exception
    Company1.append('No details available')

#Adding sleeptime    
time.sleep(2)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/3518692688.py:3: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  companies=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/a[2]")

In [324]:
#scrape location names
soup=BeautifulSoup(driver.page_source,'html.parser')
l=soup.find_all('div',attrs={'vcard'})
for i in l:
    try:
        Location1.append(i.find('small').text)
    except AttributeError :
        Location1.append("No details available")

#Adding sleeptime        
time.sleep(2)

In [325]:
#skills they hire for
try:
    skills=driver.find_elements_by_xpath("//div[@class='recInfo']/div[2]")
    for i in skills:
        Skills1.append(i.text)
except NoSuchElementException:        #handling no such element exception
    Skills1.append('No details available')

#Adding sleeptime    
time.sleep(2)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/1627405480.py:3: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  skills=driver.find_elements_by_xpath("//div[@class='recInfo']/div[2]")

In [326]:
#creating dataframe
df=pd.DataFrame({'Name':Name1,
                'Designation':Designation1,
                'Company':Company1,
                "Location":Location1,
                'Hire_for_Skillset':Skills1})
df

,Name,Designation,Company,Location,Hire_for_Skillset
0,Aakash Harit,HR Manager,Data Science Network,Delhi,"Classic ASP Developer, Internet Marketing Prof..."
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,Hyderabad / Secunderabad,".Net, Java, Data Science, Linux Administration..."
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,Pune,"Data Science, Artificial Intelligence, Machine..."
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,Ahmedabad,"Mean Stack, javascript, angularjs, mongodb, We..."
4,subhas patel,Founder CEO,LibraryXProject,UK - (london),"Hadoop, Spark, Digital Strategy, Data Architec..."
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,Vadodara / Baroda,"Analytics, Business Intelligence, Business Ana..."
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Chennai,Data Science
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,Trivandrum,"Machine Learning, algorithms, Go Getter, Compu..."
8,Asif Lucknowi,Director,Weupskill- Live Wire India,Indore,"Technical Training, Software Development, Pres..."
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,Bengaluru / Bangalore,"Software Development, It Sales, Account Manage..."
10,Priyanka Akiri,HR Manager,Infinitive Software Solutions,Hyderabad,"Oracle Dba, Data Science, Data Warehousing, ET..."
11,Kalpana Dumpala,Executive Hiring,Innominds Software,Hyderabad / Secunderabad,"Qa, Ui/ux, Java Developer, Java Architect, C++..."
12,Mubarak,Company HR,MoneyTap,Bengaluru / Bangalore,"Business Intelligence, Data Warehousing, Data ..."
13,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,Mumbai,"Office Administration, Hr Administration, tele..."
14,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,Hyderabad / Secunderabad,"Social Media, digital media maketing, seo, smm..."
15,Kapil Devang,HR Manager,BISP Solutions,Bhopal,"Big Data, Hadoop, Data Analytics, Data Science"
16,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,Chandigarh,"React.js, Data Science, Java, Front End, Busin..."
17,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,Pune,"Qlikview, Qlik Sense, Microsoft Azure, Power B..."
18,Manisha Yadav,HR Executive,Easi Tax,Navi Mumbai,"Telecalling, Client Interaction, Marketing, Re..."
19,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Cochin,Data Science
20,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,Delhi,"Corporate Sales, Software Development, Softwar..."
21,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,Hyderabad / Secunderabad,"Data Analytics, Data Science, Machine Learning..."
22,Rithika dadwal,HR Recruiter,Affine Analytics,Pune,"Data Science, Machine Learning, Python, R, Dee..."
23,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,Pune,"Big Data, Data Science, Artificial Intelligenc..."
24,Shaun Rao,Manager Human Resources,Exela Technologies,Pune,"Java, Net, Angularjs, Hr, Infrastructure, Mana..."
25,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,Pune,"Data Science, Artificial Intelligence, Machine..."
26,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,Bengaluru / Bangalore,"Software Architecture, Vp Engineering, Product..."
27,kumar,Proprietor,trainin,Bengaluru / Bangalore,"Data Science, Hadoop, Rpas, Devops, Python, Aw..."
28,Sunil Vedula,CEO,Nanoprecise Sci Corp,No details available,"Signal Processing, Machine Learning, Neural Ne..."
29,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,Delhi,"Web Technologies, Project Management, Software..."
30,Dhruv Dev Dubey,Company Recruitment Head,Confidential,Bengaluru / Bangalore,"Server Administartion, Verilog, Vhdl, Digital ..."
31,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd",Mysoru / Mysore,"Data Analytics, Managed Services, Team Leading..."
32,Avodha,Business Development Associate,Nikitha Palaparthi,Hyderabad / Secunderabad,"Ethical Hacking, Security Operations Center, S..."
33,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,Hyderabad / Secunderabad,"Data Science, Machine Learning, Big Data Analy..."
34,Priya Khare,Senior Manager,Independent Consultant,Bengaluru / Bangalore,"Data Science, Artificial Intelligence, analyti..."
35,Amit Sharma,Consultant,ASCO consulting,New Delhi,"Machine Learning, Artificial Intelligence, Dat..."
36,Kanan,senior technology instructor,NY INST,Chennai,"C, C++, Artificial Intelligence, Python, Php, ..."
37,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,Aligarh,"Relationship Management, Retail Sales, Private..."
38,Brad,"Manager, Technical Recruiting",O.C. Tanner,Salt Lake City,"Data Science, Software Engineering"
39,Rutuja Pawar,Technical Recruiter,Demand Matrix,Pune,"Data Science, Big Data Analytics, Digital Mark..."
40,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,Bengaluru / Bangalore,"Data Science, Recruitment, Salary"
41,Ankit Sinha,Head Analytics,Suntech Global,Mumbai,"B.Tech, Tableau, Statistics, R, Analytics, Tim..."
42,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,Indore,"Software Development, Business Intelligence, B..."
43,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,Bengaluru / Bangalore,"Data Science, Node.js, Angularjs"
44,Ashwini,Director Global Delivery,MRP Advisers,MYSORE,"Data Science, Media Marketing, Resource Planni..."
45,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,Hyderabad / Secunderabad,"Data Analysis, Learning, Data Science, Compute..."
46,Rajani Nagaraj,HR Manager,WildJasmine,Bengaluru / Bangalore,"Java, Hadoop, R, Machine Learning, Spark, Flum..."
47,ROHIT Kumar,Architect,LNT Private Limited,Mumbai,"Software Development, Core Java, Unit Testing,..."
48,Amir Chowdhury,Managing Partner,Granular.ai,No details available,"Machine Learning, Data Science, Product Manage..."
49,Ravi Dubey,Recruitment Manager,HyrEzy Talent Solutions LLP,Ghaziabad,Walmart Interra Skeps Expressstores indifi whi...

In [327]:
driver.close()

# . Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [328]:
#connect to webdriver
driver=webdriver.Chrome("chromedriver.exe")

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/229302933.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome("chromedriver.exe")

In [329]:
url = "https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare"
driver.get(url)

In [330]:
#scrapping book names
book_name=[]
try:
    names=driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[2]')
    for i in names:
        book_name.append(i.text)
except NoSuchElementException:              #handling no such element exception
    book_name.append('No details available')
time.sleep(2)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/805719976.py:4: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  names=driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[2]')

In [331]:
#scrapping author names
author_name=[]
try:
    names=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[3]")
    for i in names:
        author_name.append(i.text)
except NoSuchElementException:#handling no such element exception
    author_name.append('No details available')
time.sleep(2)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/2703022008.py:4: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  names=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[3]")

In [332]:
#scrapping Sale
Sale=[]
try:
    sale=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[4]")
    for i in sale:
        Sale.append(i.text)
except NoSuchElementException:#handling no such element exception
    Sale.append('No details available')
time.sleep(2)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/439037047.py:4: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  sale=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[4]")

In [333]:
#scrapping publisher
publisher=[]
try:
    publishers=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[5]")
    for i in publishers:
        publisher.append(i.text)
except NoSuchElementException:#handling no such element exception
    publisher.append('No details available')
time.sleep(2)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/742587822.py:4: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  publishers=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[5]")

In [334]:
#scrapping genre
genre=[]
try:
    genres=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[6]")
    for i in genres:
        genre.append(i.text)
except NoSuchElementException:#handling no such element exception
    genre.append('No details available')
time.sleep(2)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/2416053280.py:4: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  genres=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[6]")

In [335]:
#creating dataframe
table=pd.DataFrame({"Book_name":book_name,
                "Author_name":author_name,
                'Volume sold':Sale,
                'Publisher':publisher,
                'Genre':genre})
table

,Book_name,Author_name,Volume sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [336]:
driver.close()

# Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [337]:
#connect to webdriver
driver=webdriver.Chrome("chromedriver.exe")

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/229302933.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome("chromedriver.exe")

In [338]:
url = "https://www.imdb.com/list/ls095964455"
driver.get(url)

In [339]:
# scraping name of webseries
name=[]
try:
    names=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a")
    for i in names:
        name.append(i.text)
except NosuchElementException:#handling no such element exception
    name.append('No details available')
     
time.sleep(2)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/3787034501.py:4: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  names=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a")

In [340]:
# scraping year of release
years=[]
try:
    span=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/span[2]")
    for i in span:
        years.append(i.text)
except NosuchElementException:#handling no such element exception
    years.append('No details available')
     
time.sleep(2)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/1749906171.py:4: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  span=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/span[2]")

In [341]:
# scraping genre
genre=[]
try:
    genres=driver.find_elements_by_xpath("//span[@class='genre']")
    for i in genres:
        genre.append(i.text)
except NoSuchElementException:#handling no such element exception
    genre.append('No details available')
     
time.sleep(2)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/2828013447.py:4: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  genres=driver.find_elements_by_xpath("//span[@class='genre']")

In [342]:
# scraping run_time
run_time=[]
try:
    info=driver.find_elements_by_xpath("//span[@class='runtime']")
    for i in info:
        run_time.append(i.text)
except NoSuchElementException:#handling no such element exception
    run_time.append('No details available')
    
time.sleep(2)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/1684999199.py:4: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  info=driver.find_elements_by_xpath("//span[@class='runtime']")

In [343]:
# scraping rating
rating=[]
try:
    info=driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']/span[2]")
    for i in info:
        rating.append(i.text)
except NoSuchElementException:#handling no such element exception
    rating.append('No details available')
    
time.sleep(2)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/2611569694.py:4: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  info=driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']/span[2]")

In [344]:
# scraping votes
votes=[]
try:
    info=driver.find_elements_by_xpath("//span[@name='nv']")
    for i in info:
        votes.append(i.text)
except NoSuchElementException:#handling no such element exception
    votes.append('No details available')    
time.sleep(2)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/346841377.py:4: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  info=driver.find_elements_by_xpath("//span[@name='nv']")

In [345]:
#creating dataframe
df=pd.DataFrame({"Name":name,
                "Year_span":years,
                "Genre":genre,
                "Run_time":run_time,
                "Ratings":rating,
                "Votes":votes})
df

,Name,Year_span,Genre,Run_time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,994,203"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"1,031,713"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"949,294"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"283,634"
4,The 100,(2014– ),"Drama, Mystery, Sci-Fi",43 min,7.6,"243,418"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.4,"48,849"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"59,524"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"190,333"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"40,284"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"228,654"

# Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/
You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year
Note: - from the home page you have to go to the ShowAllDataset page through code.

In [346]:
#connect to webdriver
driver=webdriver.Chrome("chromedriver.exe")

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/229302933.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome("chromedriver.exe")

In [347]:
url = "https://archive.ics.uci.edu/"
driver.get(url)

In [348]:
#Finding view all dataset button
view_dataset = driver.find_element_by_xpath("//tbody[1]//tr/td[2]/span[2]/a")    
page_url = view_dataset.get_attribute("href")
driver.get(page_url)
time.sleep(5)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/2251025773.py:2: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  view_dataset = driver.find_element_by_xpath("//tbody[1]//tr/td[2]/span[2]/a")

In [349]:
#Getting page urls containing list of all datasets
all_lst = driver.find_element_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[1]/tbody/tr/td[2]/p/a")  
lst_url = all_lst.get_attribute("href")           
driver.get(lst_url)
time.sleep(5)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/3951575963.py:2: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  all_lst = driver.find_element_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[1]/tbody/tr/td[2]/p/a")

In [350]:
#fetching url for each dataset
data_url = driver.find_elements_by_xpath("//p[@class='normal']//b/a")    

urls = []     
for i in data_url:
    urls.append(i.get_attribute("href"))

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/3490721564.py:2: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  data_url = driver.find_elements_by_xpath("//p[@class='normal']//b/a")

In [351]:
#table view
table = driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[1]/tbody/tr/td[2]/p/a')
table.click()

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/3343852149.py:2: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  table = driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[1]/tbody/tr/td[2]/p/a')

In [352]:
#Creating empty list
Data_name = []
Data_type = []
Task = []
Attr_type = []
Instances = []
n_attributes = []
Year = []

In [353]:
#scraping dataset names
try:
    names=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a")
    for i in names:
        Data_name.append(i.text)
except NoSuchElementException:#handling no such element exception
    Data_name.append('No details available')

#Adding sleeptime
time.sleep(2)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/236465982.py:3: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  names=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a")

In [354]:
#scraping data type
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]")
    for i in info[1:]:
         Data_type.append(i.text)
except NoSuchElementException:
    Data_type.append("No information")

#Adding sleeptime    
time.sleep(2)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/2124256953.py:3: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]")

In [355]:
#scraping task names
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]")
    for i in info[1:]:
         Task.append(i.text)
except NoSuchElementException:
    Task.append("No information")

#Adding sleeptime    
time.sleep(2)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/746101223.py:3: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]")

In [356]:
#scraping Attribute type
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]")
    for i in info[1:]:
         Attr_type.append(i.text)
except NoSuchElementException:
    Attr_type.append("No information")

#Adding sleeptime    
time.sleep(2)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/2642524818.py:3: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]")

In [357]:
#scraping No of instances
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]")
    for i in info[1:]:
         Instances.append(i.text)
except NoSuchElementException:
    Instances.append("No information")

#Adding sleeptime    
time.sleep(2)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/2326169705.py:3: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]")

In [358]:
#scraping No of attribute
no_of_attributes=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]")
    for i in info[1:]:
         n_attributes.append(i.text)
except NoSuchElementException:
    n_attributes.append("No information")

#Adding sleeptime    
time.sleep(2)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/3318513129.py:4: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]")

In [359]:
#scraping Year
year=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]")
    for i in info[1:]:
         Year.append(i.text)
except NoSuchElementException:
    Year.append("No information")

#Adding sleeptime    
time.sleep(2)

C:\Users\Nirav\AppData\Local\Temp/ipykernel_9760/3843781627.py:4: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]")

In [360]:
#creating dataframe
df=pd.DataFrame({'Dataset_Name':Data_name,
                'Data_type':Data_type,
                'Task':Task,
                'Attribute_type':Attr_type,
                'No_of_instances':Instances,
                'No_of_attributes':n_attributes,
                'Year':Year})
df

,Dataset_Name,Data_type,Task,Attribute_type,No_of_instances,No_of_attributes,Year
0,2.4 GHZ Indoor Channel Measurements,Multivariate,Classification,Real,7840,5,2018
1,"3D Road Network (North Jutland, Denmark)","Sequential, Text","Regression, Clustering",Real,434874,4,2013
2,3W dataset,"Multivariate, Time-Series","Classification, Clustering","Integer, Real",1984,8,2019
3,9mers from cullpdb,Sequential,"Classification, Regression",Real,158716,4,2021
4,: Simulated Data set of Iraqi tourism places,Multivariate,"Classification, Clustering",,232,16,2020
...,...,...,...,...,...,...,...
617,Youtube cookery channels viewers comments in H...,"Multivariate, Text",Classification,,9800,3,2019
618,YouTube Multiview Video Games Dataset,"Multivariate, Text","Classification, Clustering","Integer, Real",120000,1000000,2013
619,YouTube Spam Collection,Text,Classification,,1956,5,2017
620,Z-Alizadeh Sani,,Classification,"Integer, Real",303,56,2017
621,Zoo,Multivariate,Classification,"Categorical, Integer",101,17,1990

In [361]:
driver.close()